[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600
requires = ["Multiplayer"]

[[patches]]
[patches.regex]
target = 'game.lua'
pattern = 'if MP.LOBBY.code then(.|\n)*?MP.shared = nil\n\t\tend\n'
position = 'at'
payload = ''
times = 1
