[manifest]
version = "1.0.0"
dump_lua = true
priority = 3

# New tab for Special Techniques on colection
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "UIBox_button({button = 'your_collection_jokers', label = {localize('b_jokers')}, count = G.DISCOVER_TALLIES.jokers,  minw = 5, minh = 1.7, scale = 0.6, id = 'your_collection_jokers'}),"
position = 'after'
match_indent = true
payload = '''
--UIBox_button({button = 'your_collection_techniques', label = {localize('ina_special_technique')}, count = G.DISCOVER_TALLIES.techniques, minw = 5, id = 'your_collection_techniques'}),
UIBox_button({button = 'your_collection_managers', label = {localize('ina_special_manager')}, count = G.DISCOVER_TALLIES.managers, minw = 5, id = 'your_collection_managers'}),
'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "jokers = {tally = 0, of = 0},"
position = 'before'
match_indent = true
payload = '''
techniques = {tally = 0, of = 0},
managers = {tally = 0, of = 0},
'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if v.set and ((v.set == 'Joker') or v.consumeable or (v.set == 'Edition') or (v.set == 'Voucher') or (v.set == 'Back') or (v.set == 'Booster')) then"
position = 'at'
match_indent = true
overwrite = true
payload = '''
if v.set and (
    (v.set == 'Joker' and v.ptype) or
    v.consumeable or
    (v.special and (v.special == "Technique" or v.special == "Manager")) or
    (v.set == 'Edition') or
    (v.set == 'Voucher') or
    (v.set == 'Back') or
    (v.set == 'Booster')
) then'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if v.set and v.set == 'Joker' then"
position = 'before'
match_indent = true
payload = '''
if v.special and v.special == "Technique" then
    G.DISCOVER_TALLIES.techniques.of = G.DISCOVER_TALLIES.techniques.of+1
    if v.discovered then 
        G.DISCOVER_TALLIES.techniques.tally = G.DISCOVER_TALLIES.techniques.tally+1
    end
end
if v.special and v.special == "Manager" then
    G.DISCOVER_TALLIES.managers.of = G.DISCOVER_TALLIES.managers.of+1
    if v.discovered then 
        G.DISCOVER_TALLIES.managers.tally = G.DISCOVER_TALLIES.managers.tally+1
    end
end
'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if v.set and v.set == 'Joker' then"
position = 'at'
overwrite = true
match_indent = true
payload = '''
if v.set and v.set == 'Joker' and v.special == nil and v.ptype then
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "local alert_joker, alert_voucher, alert_tarot, alert_planet, alert_spectral, alert_blind, alert_edition, alert_tag, alert_seal, alert_booster = false,false,false,false,false,false,false,false,false,false"
position = 'at'
overwrite = true
match_indent = true
payload = '''
local alert_manager, alert_technique, alert_joker, alert_voucher, alert_tarot, alert_planet, alert_spectral, alert_blind, alert_edition, alert_tag, alert_seal, alert_booster = false,false,false,false,false,false,false,false,false,false,false,false
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "if v.set == 'Joker' then alert_joker = true end"
position = 'at'
match_indent = true
payload = '''
if v.set == 'Joker' and not v.special then alert_joker = true end
if v.set == 'Joker' and v.special and v.special == "Technique" then alert_technique = true end
if v.set == 'Joker' and v.special and v.special == "Manager" then alert_manager = true end
'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if v.set == 'Joker' and not v.no_collection and not v.omit then"
position = 'at'
match_indent = true
payload = '''
if v.set == 'Joker' and not v.no_collection and not v.omit and v.mod and v.mod.id == 'Pokerleven' then
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "{id = 'your_collection_boosters', alert_uibox_name = 'your_collection_boosters_alert'},"
position = 'after'
match_indent = true
payload = '''
{id = 'your_collection_techniques', alert_uibox_name = 'your_collection_techniques_alert'},
{id = 'your_collection_managers', alert_uibox_name = 'your_collection_managers_alert'},
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "G.ARGS.set_alerts_alertables[11].should_alert = alert_booster"
position = 'after'
match_indent = true
payload = '''
G.ARGS.set_alerts_alertables[12].should_alert = alert_technique
G.ARGS.set_alerts_alertables[13].should_alert = alert_manager
'''
