[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Add field spell area to joker evaluation
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = 'before'
match_indent = true
payload = '''
if Pokerleven and Pokerleven.ina_manager_area and type(Pokerleven.ina_manager_area.cards) == "table" then
    table.insert(t, Pokerleven.ina_manager_area)
end
'''

# Add joker to managers when buying from the shop
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.jokers:emplace(c1)"
position = 'at'
match_indent = true
payload = '''
if Pokerleven and Pokerleven.is_manager(c1) then
    Pokerleven.add_to_managers(c1)
else
    G.jokers:emplace(c1)
end
'''

# Change other_joker key
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "-- TARGET: add context.other_something identifier to your cards"
position = 'before'
match_indent = true
payload = '''
if Pokerleven and Pokerleven.is_manager(_card) then other_key = 'other_manager' end
'''

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''print("ERROR LOADING GAME: Card area '"..k.."' not instantiated before load") end'''
position = 'at'
match_indent = true
payload = '''
local skip_print = k == "shop_jokers" or k == "shop_vouchers" or k == "shop_booster"
    if not skip_print then
        print("ERROR LOADING GAME: Card area '" .. k .. "' not instantiated before load")
    end
end
'''
